Feature/001 login
masato5579/e-share pull request #6
Opened 2021-12-19 07:56 UTC by masato5579

@Apro-yuto 
長島さん

一旦、e-mailでログインできるようにしました。

## 変更点
- laravel-breezeのデフォルトのデザインの削除
- mailhogの導入
- ログアウト時にloginページに遷移するように
- 簡単なメタタグの設定
- .env_testingのgitignoreへの追加（後でreadmeに手順を書きます。）
etc...

## laravel-breezeに下記の機能が備わっていたので、その機能はそのままにしています。
- signIn(register)
- login
- パスワードリセット
- パスワードリセットメール送信
- メール確認機能
etc...

**laravel-breezeをインストールしたので、
レビューされる際は、composer installをお願いいたします。**

初期の環境構築で整いきれていないものを
別ブランチで作成するのも面倒でしたので、このブランチで作成しました。
1ブランチに詰め込みすぎてしまい申し訳ないのですが、
レビューのほど、よろしくお願いいたします。

2022-01-03 07:27 UTC, Apro-yuto requested changes
reviewer機能が強化されててReview確定しなかったらassignerに見れないぽい、、
遅れてすいませんお願いします！

2022-01-03 07:27 UTC, Apro-yuto commented on resources/views/auth/register.blade.php
> +    <x-auth-validation-errors class="" :errors="$errors" />
`class=""`
classを付与しなければ、属性は消してください。

2022-01-03 07:27 UTC, Apro-yuto commented on resources/views/auth/register.blade.php
> +    <x-auth-validation-errors class="" :errors="$errors" />
以降もお願い！

2022-01-03 07:27 UTC, Apro-yuto commented on app/Providers/RouteServiceProvider.php
> +    public const HOME = '/dashboard';
`public const HOME = '/home';`　に戻してください！

2022-01-03 07:27 UTC, Apro-yuto commented on routes/web.php
> +Route::get('/dashboard', function () {
`/home`に遷移するように変更してください。

2022-01-03 07:27 UTC, Apro-yuto commented on docker-compose.yml
> +      test: ["CMD", "mysqladmin", "ping", "-p$a{DB_PASSWORD:-password}"]
`a`ってなんだ、、、？

2022-01-03 07:27 UTC, Apro-yuto commented on resources/views/auth/reset-password.blade.php
> +            <form method="POST" action="{{ route('password.update') }}">
[Editorconfig](https://github.com/masato5579/e-share/blob/feature/001-login/.editorconfig)でインデントサイズを2にしてください！

2022-01-05 15:22 UTC, masato5579 commented on resources/views/auth/reset-password.blade.php
> +            <form method="POST" action="{{ route('password.update') }}">
@Apro-yuto 
Editorconfigで設定してもうまくいかなかったので、
bladeのLintパッケージ（blade-formatter）をインストールしてnpm run devをすると実行されるようにしました。
また、ciにも入れてます。

2022-01-05 15:38 UTC, masato5579 commented
@Apro-yuto 

ご指摘いただいた点、全て修正したので、念の為、ご確認お願いします。

2022-01-08 05:40 UTC, Apro-yuto requested changes

2022-01-08 05:40 UTC, Apro-yuto commented on routes/web.php
>  })->middleware(['auth'])->name('dashboard');
`->name('dashboard');`
ここは
`->name('home.index');`
のようにするとメンテナンス性が上がるかもです。

homeを表示する(GET)ルートと、homeにデータを送信(POST)するルートなどの、Homeに属するルートが複数存在した場合のことを考えたら以上の書き方にするとまとめやすいです。

例)
```
Route::get('/home', function () {
    return view('home');
})->middleware(['auth'])->name('home.index');

Route::get('/home/{user?}/detail', function () {
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
})->middleware(['auth'])->name('home.detail');

Route::post('/home', function (Request $req) {
    ~~~~~~~~~~~~~~~~~~~~~
})->middleware(['auth'])->name('home.post');
```

2022-01-08 05:46 UTC, Apro-yuto commented on routes/web.php
>  })->middleware(['auth'])->name('dashboard');
groupにまとめるのもありですね。

```
Route::group(['middleware' => 'auth', 'as' => 'home.'],function ()
{
  Route::get('/home', function () {
      return view('home');
  })->name('index');

  Route::get('/home/{user?}/detail', function () {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  })->name('detail');

  Route::post('/home', function (Request $req) {
      ~~~~~~~~~~~~~~~~~~~~~
  })->name('post');
});
```

2022-01-08 05:57 UTC, masato5579 commented on routes/web.php
>  })->middleware(['auth'])->name('dashboard');
なるほどです。
参考Qiita : https://qiita.com/kazuhei/items/935257b0d72fa314d461

修正しました！
他指摘するところありましたら、なんなりとお申し付けください。

2022-01-08 06:03 UTC, merged